# Generated by Django 4.2 on 2023-05-02 21:58
import random
from django.db import migrations
from core.models import Business, Person, Affiliation, Industry, Lead

lorem_ipsum = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."


def random_name():
    first_names = ['Alice', 'Bob', 'Charlie', 'David', 'Emma', 'Frank', 'Grace', 'Henry', 'Isabel', 'Jack', 'Kate', 'Liam', 'Mia', 'Nathan', 'Olivia', 'Patrick', 'Quinn', 'Rachel', 'Samuel', 'Taylor', 'Uma', 'Victoria', 'William', 'Xavier', 'Yvonne', 'Zachary']
    last_names = ['Adams', 'Baker', 'Carter', 'Davis', 'Edwards', 'Foster', 'Garcia', 'Harris', 'Ingram', 'Johnson', 'Khan', 'Lee', 'Martin', 'Nguyen', 'Owens', 'Patel', 'Qin', 'Robinson', 'Smith', 'Thompson', 'Upton', 'Vargas', 'White', 'Xu', 'Yang', 'Zhang']

    first_name = random.choice(first_names)
    last_name = random.choice(last_names)

    return f"{first_name} {last_name}"

def seed_example_data(apps, schema_editor):
    print("Starting Seed...")

    Business = apps.get_model("core", "Business")
    Person = apps.get_model("core", "Person")
    Affiliation = apps.get_model("core", "Affiliation")
    Industry = apps.get_model("core", "Industry")
    Lead = apps.get_model("core", "Lead")

    businesses = []

    for i in range(100):
        business = Business.objects.create(name=f"Business {i}", description=lorem_ipsum)
        businesses.append(business)

    for business in businesses:
        num_persons = random.randint(1, 3)
        for i in range(num_persons):
            name = random_name()
            person = Person.objects.create(about_me=lorem_ipsum, full_name=name, profile_img_url=f"https://robohash.org/{name}/")
            Affiliation.objects.create(person=person, business=business, is_owner=i==0)

    # Create some industries
    industry_names = ["Technology", "Finance", "Healthcare", "Retail", "Manufacturing"]
    industries = [Industry.objects.create(name=name) for name in industry_names]

    # Assign random industries to businesses
    for business in businesses:
        num_industries = random.randint(1, len(industries))
        selected_industries = random.sample(industries, num_industries)
        for industry in selected_industries:
            business.industries.add(industry)

    # Create some leads
    for business in businesses:
        if random.randint(0, 5) >=3:
            Lead.objects.create(business=business, is_favorite=random.choice([True, False]))

    print("Seed complete.  Good luck on the interview!")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_example_data),
    ]
